### ISSUE TITLE
HllDruidCombine invalid payloadstart position

### ISSUE THREAD

**Issue by frankgrimes97** [criteo/vertica-hyperloglog#14]
Hi,

I'm using the Druid HLL java implementation to compute HLL values in a Spark job and I'm inserting that output into a `VARBINARY(1031)` column. (https://github.com/apache/incubator-druid/blob/master/hll/src/main/java/org/apache/druid/hll/HyperLogLogCollector.java)

My insert uses a vertica COPY command with `FORMAT 'HEX'`, and I'm serializing it as follows:

`javax.xml.bind.DatatypeConverter.printHexBinary(hyperLogLogCollector.toByteArray())`

Then, when I use `HllDruidCombine` in a select statement I'm getting the following error:

`Caused by: java.sql.SQLNonTransientException: [Vertica][VJDBC](5861) ERROR: Error calling aggregateArrs() in User Function HllDruidCombine at [/usr/local/vertica-hyperloglog/SOURCES/src/HllDruidCombine.cpp:73], error code: 0, message: Exception while aggregating intermediates: [invalid payloadstart position:65529]`

Are there any known incompatibilities between the two implementations?
Or, am I perhaps doing something wrong?

Any help or hints would be appreciated!

Thanks!

**Comment by freakyzoidberg** [comment]
That sound correct and should be supported (assuming those are HLLCV1 - eg not a very old version of druid as there is no support for HLLCV0)

Do you mind sharing an example of synopsis which fails?
(given the error it should fail on the distinct count too)

**Comment by frankgrimes97** [comment]
Ah, I just discovered that the error occurs when the HLL VARCHAR column is null!

**Comment by frankgrimes97** [comment]
```
adgear=> SELECT HllDruidCombine(NULL);
ERROR 5861:  Error calling aggregateArrs() in User Function HllDruidCombine at [/usr/local/vertica-hyperloglog/SOURCES/src/HllDruidCombine.cpp:73], error code: 0, message: Exception while aggregating intermediates: [invalid payloadstart position:17710]
```

**Comment by frankgrimes97** [comment]
Ok, I solved my `NULL` issue and now `HllDruidDistinctCount` works but `HllDruidCombine` still gives me `invalid payloadstart position`

**Comment by frankgrimes97** [comment]
Seems to fail when grouping/ordering by a different column.
This works:

```
SELECT HllDruidDistinctCount(hll_druid) AS uniques_approx_druid, HllDruidDistinctCount(hll_clicks_druid) AS unique_clicks_approx_druid FROM (SELECT HllDruidCombine(hll_druid) AS hll_druid, HllDruidCombine(hll_clicks_druid) AS hll_clicks_druid FROM tmptable f) inner_query;

 uniques_approx_druid | unique_clicks_approx_druid 
----------------------+----------------------------
               305126 |                       1081
(1 row)
```

This fails:

```
SELECT frequency, HllDruidDistinctCount(hll_druid) AS uniques_approx_druid, HllDruidDistinctCount(hll_clicks_druid) AS unique_clicks_approx_druid FROM (SELECT frequency, HllDruidCombine(hll_druid) AS hll_druid, HllDruidCombine(hll_clicks_druid) AS hll_clicks_druid FROM tmptable f GROUP BY 1 ORDER BY 1) inner_query GROUP BY 1 ORDER BY 1;

ERROR 5861:  Error calling aggregateArrs() in User Function HllDruidDistinctCount at [/usr/local/vertica-hyperloglog/SOURCES/src/HllDruidDistinctCount.cpp:66], error code: 0, message: Exception while aggregating intermediates: [invalid payloadstart position:65535]
```

**Comment by freakyzoidberg** [comment]
So yeah two bugs ...

For the NULL, technically that's invalid, either should be treated as empty count or at minima fail early and explicitly (there are some null pointer dereference here).

For the second issue, just ran some tests and in some cases it did fail like you showed.

Seems there is an issue where some dense synopsis are treated as sparse, 
can you run the following and see if that works (obviously the result will be incomplete as it discard some rows)
```
SELECT frequency, HllDruidDistinctCount(hll_druid) AS uniques_approx_druid FROM (SELECT frequency, HllDruidCombine(hll_druid) AS hll_druid FROM tmptable f GROUP BY 1 ORDER BY 1) inner_query where length(hll_druid) > 1000 GROUP BY 1 ORDER BY 1;
```

That second one is to be fixed asap

**Comment by freakyzoidberg** [comment]
Found the bug, will submit the patch tomorrow. Thanks for that!
(In the serialization of sparse format)
