### ISSUE TITLE
Causes node crash when using Vertica 9

### ISSUE THREAD

**Issue by devdazed** [criteo/vertica-hyperloglog#7]
built your library using GCC 4.9 on Ubuntu 16.10 and installed it on Vertica 9
```
dbadmin=> select version();
              version
------------------------------------
 Vertica Analytic Database v9.0.1-2
```

running this command as a small test:
```
dbadmin=> SELECT HLLCreateSynopsis(user_id) FROM (select user_id FROM vt_fact_article_events LIMIT 10) t;
```
Caused the Vertica process to lock up and become unresponsive.  Remediation was to kill the Vertica process on the host and restart it using admintools.

**Comment by freakyzoidberg** [comment]
Closing this, the issue with memory allocation was addressed
