### ISSUE TITLE
Missing feature / misleading documenation

### ISSUE THREAD

**Issue by david-kubecka** [criteo/vertica-hyperloglog#9]
Hi,

in the readme file there's a section describing the available UDFs.

> This repository contains implementation of two User Defined Aggregation Functions in Vertica: HllCreateSynopsis and HllDistinctCount. The former is used to aggregate input data and creates a synopsis in the format described above. **These synopsis can be further aggregated to summarize unions of two or more data sets.**

How can be this aggregating (merging) of synopsis to obtain another synopsis achieved? I know that the HLL algorithm should enable this and indeed some implementations of HLL offer this, e.g. https://cloud.google.com/bigquery/docs/reference/standard-sql/functions-and-operators#hll_countmerge_partial.

**Comment by freakyzoidberg** [comment]
Hi David,

We actually have a HllCombine function that would do what you describe, which should land in this repo in the next few days among other bug fixes & improvements

**Comment by freakyzoidberg** [comment]
Closing this, there is now a Combine function

**Comment by david-kubecka** [comment]
@freakyzoidberg That's greate news! I will pass it to my team.

Just one small request: can we have also some examples of how the new HllCombine function is used? Also mentionining its limitations (if any).
